# Introduction

Melt of the seasonal mountain snowpack is an important source of streamflow across the globe, crucial for downstream ecosystems, energy production, and agricultural irrigation [@Viviroli2007; @Derksen2019]. The high albedo and energy required to melt snow also provides a large-scale cooling effect for our planet by reflecting most of the incoming solar radiation and dissipating energy during spring melt [@Henderson2018]. Despite this importance, there is uncertainty in estimates of snow accumulation, especially in mountain forests, due redistribution of snow by wind and forest canopy [@Rutter2009; @Krinner2018; @Ellis2010]. In western Canada, diverse topography, climate and canopy structure results in highly variable snow accumulation, which presents a challenge in predicting the quantity of snow available for streamflow and downstream water resources [@Pomeroy1995; @Ellis2010]. In the Northern Hemisphere, over 50% of snowmelt-dominated basins are covered by needleleaf forest [@Kim2017]. This extensive canopy coverage reduces the amount of snow that is available for streamflow through interception of snowfall and subsequent ablative processes [@Hedstrom1998; @Essery2003; @Ellis2010]. Intercepted snow in the canopy is subjected to higher rates of sublimation compared to subcanopy snow due to greater surface area, turbulent energy exchange, and solar exposure [@Pomeroy1998b]. Across the Northern Hemisphere, researchers estimate that 25 to 45% of annual snowfall may be lost to the sublimation of intercepted snow from the canopy [@Essery2003]. However, the time that snow resides in the canopy and is subject to sublimation is dependent on rates of unloading, melt, drip, and resuspension of snow. These processes lead to the spatial and temporal diversity in subcanopy snowpack accumulation and contribute to the higher uncertainty for the forested domain of hydrological models [@Rutter2009; @Krinner2018].

The high variability of snow accumulation in forests is not well represented due to a sparse and unrepresentative network of in situ observations, which are mostly located in clearings [@Vionnet2021]. Moreover, observing snow accumulation under forest canopies at large extents remains uncertain with current remote sensing technologies [@Rittger2020]. There is a need for reliable models of snow redistribution by forest and wind to estimate snow accumulation in mountains [@Pomeroy2007; @Rutter2009; @Clark2015]. Existing snow interception parameterisations have been developed for both warm maritime [@Storck2002; @Andreadis2009] and cold continental [@Hedstrom1998; @Ellis2010; @Roesch2001] climates characterized by dense forest canopy. Accurate simulations of forest snow accumulation is often achieved if the parameterisations are applied in similar climates to where they were developed [@Lundquist2021; @Roth2019; @Rasouli2019b] or if they are combined into a hybrid parameterisation and assessed at global and regional scales in a wide range of climates [@Essery2003; @Gelfan2004]. Although accurate performance has been achieved across different climates in some studies [@Essery2004; @Gelfan2004], other snow model comparisons [@Krinner2018; @Rutter2009] have shown reduced performance. The decision in earth system models to use parameterisations derived in warm or cold climates is often based on a simple temperature-based step function [@Essery2003; @Gelfan2004] and may require modification to better represent more transitional climates and forest types. The omission or simplified representation of processes and reliance on empirical calibrations likely contribute to model uncertainty when applied in climates and forests where other processes become important [@Rutter2009; @Krinner2018; @Lumbrazo2022; @Roth2019; @Moeser2015; @Lundquist2021]. 
  
Some of the processes currently not encoded in snow interception models include wind redistribution of snow during interception, rain on intercepted snow, hoarfrost, rime ice and the cohesion and adhesion of snow in the canopy. @Roesch2001 and @Bartlett2015 created a wind unloading function for canopy snow that is based on measurements of snow albedo from @Betts1997 as an index for canopy snow ablation (i.e., unloading, melt, and sublimation) in a low wind environment of the boreal forest in Saskatchewan. However, @Pomeroy1996 found the relationship between albedo and intercepted snow load was not discernible for the same forest as the @Betts1997 study. Moreover, it is unclear the influence of sublimation and melt processes on the canopy snow ablation proxy measurement. @Pomeroy1996 used careful radiation measurements and snow loads from a weighed suspended tree and challenge the @Betts1997 observations the @Roesch2001 parameterisation is based on. @Lumbrazo2022 provide a more recent assessment of canopy snow wind redistribution and provide the the first uncalibrated test of the @Roesch2001 wind induced unloading parameterisation. The results from @Lumbrazo2022 generally showed poor performance in mountain forests of Colorado and Washington. @Lumbrazo2022 additional process investigation on the influence of wind on canopy snow interception is required to better simulate mountain forest SWE accumulation. 

The calculation of canopy snow melt is often oversimplified in many snow interception models. For example, [@Pomeroy2007; @Ellis2010; @Essery2016] use empirical time-based melt calculations to melt snow intercepted in the canopy. While @Clark2020 and @Verseghy2017 use a physically based energy balance model to melt snow in the canopy, both models assume that the surface temperature of vegetative elements are in equilibrium with snow intercepted in the canopy. This simplification likely leads to a positive bias in canopy snow melt predictions as the vegetative elements are known to have higher temperatures than snow clumps [@Pomeroy2009]. Once the canopy snow is at 0 째C and is melting, intercepted snow will reach the ground as clumps of wet snow or will drip as liquid water to the ground [@Storck2002]. The distinction between wet snow or liquid meltwater has important implications for the energy balance of the snowpack beneath the canopy, as liquid meltwater can add a large amount of advective energy. However, predicting the ratio of solid to liquid water unloading due to canopy snow melt remains an area of uncertainty [@Roesch2001; @Storck2002].

Future climate change is expected to change the dominant hydrological processes in mountain forests [@He2021; @Dettinger2014; @Viviroli2011; @Fang2020b]. A report by Environment and Climate Change Canada [@Bush2019], suggest an increase in air temperature of 2 째C from the 1986-2005 reference period by 2050 for the low emission scenario and 6 째C for the high emission scenario by the late 21^st^ century. @Bush2019 project an increase in annual mean precipitation over all of Canada during the second half of the 21^st^ century, with a larger increase in northern Canada. As the climate warm canopy snow melt and drip processes will likely become more common. However, since melt and drip of canopy snow is not well represented in current hydrological models, additional investigations are required to better understand these processes that are expected to become more prevalent with climate change. 

Climate change is also expected to have profound effects on forest ecology which presents problems for snow interception parameterisations that have coefficients derived from individual sites and applied globally without change. Large portions of the boreal forest have been found to be experiencing significant ecosystem change and has been attributed to browning from drought [@Dai2013], disease [@Ruess2021], insects [@Kurz2008], and fire [@Kasischke2006; @Kasischke2010]. Following these disturbances greening occurs, which increases forest density in the disturbed regions [@Sulla2018; @Ju2016; @Keenan2018; @Lantz2019]. Across the globe, mountain ecosystems have also observed rapid vegetation changes with evidence for an increase in warm-adapted species and reduction in cold-adapted species [@Gottfried2012]. These changes in temperature, precipitation and forest ecology are expected to have strong modifications on how intercepted snow is partitioned through sublimation, unloading and drip [@He2021]. This introduces uncertainty when parameterisations and coefficients, developed in a 20th century climate are applied to new climates and forest ecosystems that are arising in the 21st century.

These rapid changes of climate and forest ecology illustrate the pressing need to assess whether existing snow interception parameterisations are suitable for the uncalibrated application across diverse forest ecosystems and climates. If the physical processes important for snow interception are adequately represented in existing parameterisations, then more accurate model performance should be expected across diverse environments [@Pomeroy2013a; @Clark2016]. Therefore, the theory and assumptions of existing parameterisations need to be tested across variable climate and forest structures to ensure their applicability in these environments and whether modification is required. This will ascertain where current processes representations work and what processes are not presently included that should be. 

To achieve this, first the theoretical underpinnings and assumptions of existing parameterisations must be tested across forests that have variable canopy cover, wind speed, and air temperatures. Previous work by @Gelfan2004, has shown the [@Hedstrom1998; @Pomeroy1998b] snow interception parameterisation to perform well when coupled with the @Storck2002 wet-snow unloading and drip algorithm in northwestern Russia which frequently transitioned from 0 to -20째C in canopy cover ranging from 0.6 to 0.7. However, aside from the @Gelfan2004 study, the evaluation of snow interception parameterisations has been limited and few studies have investigated their performance in mountain forests. Therefore, in-situ measurements are needed of canopy snow interception and the subsequent ablation of canopy snow in differing mountain climates (warm, transitional and cold) and forest structures (sparse to dense). These measurements will be used to test the theoretical underpinnings of existing parameterisations for application across environments that have differing processes important for forest snow redistribution.

To assess the performance of existing parameterisations, a modular and flexible model platform will be used to simulate the individual mass and energy balance fluxes and states of the canopy and snowpack. The advantage of modular and flexible model platforms is that it is possible to adjust process parameterisations while holding the remaining model parameters and mass and energy conservation equations constant [@Pomeroy2007; @Clark2015]. The Cold Regions Hydrological Model platform [CRHM, @Pomeroy2007] will be used in this study as its snow interception algorithms have been successfully used in previous studies [@Ellis2010; @Pomeroy2012; @Rasouli2019b; @Sanmiguel2022] to assess snow interception processes in Spain, USA, and Canada (Alberta, Idaho, Yukon, and Saskatchewan). Since CRHM is a process-based model agnostic platform, individual state and flux variables including subcanopy snow accumulation, snow interception, sublimation, unloading, drip, and wind redistribution can be evaluated using differing parameterisations. To evaluate existing parameterisations of snow interception [@Hedstrom1998;@Storck2002;@Andreadis2009], and ablation of canopy snow by unloading [@Ellis2010; @Roesch2001; @Andreadis2009], drip [@Storck2002;@Andreadis2009; @Ellis2010] and sublimation [@Pomeroy1998b] CRHM will be run at four mountain forest research basins across western Canada and compared to in-situ observations. Insights gained from an evaluation of the theoretical underpinnings and assumptions on new and archival field observations will help inform the improvement of existing snow interception process representations. Modifications to the existing parameterisations to better represent snow interception processes will be validated on the associated change in error in simulated and observed forest snow accumulation and streamflow.

## Research Objectives and Questions

The overarching goal of this thesis is to better understand the dominant processes that govern snow accumulation in forested environments and acertain how these processes can be best represented in hydrological models. Two research objectives guide this thesis: First evaluate the suitability of existing snow interception and ablation parameterisations for application in needleleaf forests with differing canopy structure and meteorology. Second, Determine how new snow interception and ablation parameterisations could enhance the representation of processes important for subcanopy snow accumulation. To facilitate these objectives the following research questions will be answered through four separate journal aticles:

1. What are the theoretical underpinnings and assumptions behind existing snow interception and ablation parameterisations?  
   
2. Are the theories and assumptions of existing snow interception parameterisations supported by field measurements collected across diverse canopy structures and meteorological conditions?  
   
3. Are the theories and assumptions of existing canopy snow ablation parameterisations supported by field measurements collected across varying meteorological conditions?  

4. How can the use of novel snow interception parameterisations enhance simulations of snow accumulation in forests with differing tree species, canopy structures, and meteorological conditions?

## Organization of Chapters

This thesis contains six chapters, the afforementioned research questions are addressed following the Introduction through the research articles presented in chapters two through five. The final chapter, Chapter 6 includes the synthesis and conclusions. 

The second chapter corresponds to the first research question and consists of a comprehensive review of the literature focused on snow interception and ablation parameterisations. This review provides the scientific background and context related to the topic of this thesis by identifying the theoris and assumptions that underly existing parameterisations and helps identify the primary research gaps which this thesis aims to address. One outcome of this chapter is identifying inconsistencies with existing parameterisations largely based on assumptions and limitations on in-situ observations related to isolating individual processes such as throughfall, unloading, and or drip.

After identifying the theories underyling both interception and canopy snow ablation parameterisations in chapter 2 these theories were evaluated using novel in-situ observations of interception and ablation. A key theme emerged from chapter 2 regarding distinguishing individual processes in observations which informed the methodology underlying chapter 3 which aimed to quantify canopy snow interception prior to canopy snow ablation over both high-spatial and temporal resoluation. Moreover, novel canopy density metrics which take into account the trajectory of incoming snowfall, building on previous work in the literature, helped better describe the initial interception prpcess compared to previous parameterisations. Existing theories failed to represent the dominant processes observed at this site, either due to an overestimate of the antecedent snowload on throughfall amounts [@Storck2002; @Hedstrom1998] or constant throughfall rates across differing canopy densities [@Storck2002], thus addressing research question 2. These inconsistencies of existing theories provided impetus to develop two new parameterisations to describe canopy density and interception of snow in the canopy prior to ablation.

Chapter 4 addresses research question three and revealed that existing theories to represent canopy snow unloading, melt, and drip differed from new observations of canopy snow ablation collected as part of this study. While the broad theme of canopy snow ablation aligned with existing theories on the importance of representing both dry and melt-induced unloading the underlying explanatory varibles for either process differed from existing studies. The new observations collected as part of Chapter 4 revealed that canopy snow load, wind shear stress, and canopy snowmelt were strongly associated with unloading. This differed from existing approaches which calculate unloading as a function of wind speed, temperature, and do not adjust the ratio of canopy snowmelt to drip as a function of snow load.

Based on the results from Chapter 3 and 4 that existing theories to represent snow interception and ablation are inconsistent with observations from this study. A new canopy snow model was developed to incorporate new relationships to represent snow interception and canopy snow ablation. The new model was implemented in the Cold Regions Hydrological Modelling Platform at four research sites spanning western and northern Canada to provide case studies on the validation of the new parameterisations ability to simulate subcanopy snow water equivilent and to showcase the new model as a diagnostic tool for understanding snow-vegatation interactions in varying climate and forest canopy types. The updated model was found to improve simulations of subcanopy SWE across all four sites with the largest improvement under warm-humid maritime climate dominated by canopy snow melt regimes rather than sublimation, thus addressing the fourth research question. 

The main philosophical argument that this thesis presents is that computational approximations of hydrological processes should represent individual dominant processes where possible. This allows for improved process diagnosis and compatibility amongst differing parameterisations. Alternatively parameterisations that represent differing degrees of different processes hinder the mixing and matching facilitated by hydrological model platforms. 

\pagebreak
