
## Appendix {#sec-appendix}

### Snow Interception Parameterization Derivations

The original formulation of @Hedstrom1998a is:

$$
\frac{I}{P}(L) = C_{lca} \frac{L_{max}-L_0-\Delta L}{L_{max}}
$$ {#eq-hp98-int-orig}

where $L_0$ (kg m^-2^), is the canopy snow load before snowfall is added to the canopy, $\Delta L$ (kg m^-2^), is the change in canopy snow load due to snowfall. @eq-hp98-int-orig is written in this way in @Hedstrom1998a since they had measurements of $L_0$ at the beginning of the storm. However, this equation further simplified here since:

$$
L = L_0 + \Delta L
$$

and therefore:

$$
\frac{I}{P}(L) = C_{lca}\frac{L_{max}-L}{L_{max}}
$$

The derivation of the @Hedstrom1998a snow interception parameterization, @eq-hp98-int-numeric, from @eq-hp98-int-smpl is provided by first combining @eq-ip and @eq-hp98-int-smpl1:

$$
\frac{dL}{q_{sf} dt} = C_{lca}\frac{L_{max}-L}{L_{max}}
$$ {#eq-hp98-int-smpl}

$$\frac{1}{L_{max}-L} dL = \frac{C_{lca}}{L_{max}} q_{sf} dt$$

$$
\int^{L_1}_{L_0}\left[\frac{1}{L_{max}-L}\right] dL =\frac{C_{lca}}{L_{max}} \overline{q_{sf}} \int^{t_1}_{t_0} dt $$ $$-ln\left(\frac{L_{max}-L_1}{L_{max}-L_0}\right)  = \frac{C_{lca}}{L_{max}} \overline{q_{sf}} \Delta t $$ $$\frac{L_{max}-L_1}{L_{max}-L_0} = exp \left(-\frac{C_{lca}}{L_{max}} \overline{q_{sf}} \Delta t \right)$$ $$1-\frac{L_{max}-L_1}{L_{max}-L_0} = 1- exp \left(-\frac{C_{lca}}{L_{max}} \overline{q_{sf}} \Delta t \right)$$ $$(L_{max}-L_0)-(L_{max}-L_1) = (L_{max}-L_0)\left(1- exp \left(-\frac{C_{lca}}{L_{max}} \overline{q_{sf}} \Delta t \right) \right)$$

$$\Delta L = (L_{max}-L_0)\left(1- exp \left(-\frac{C_{lca}}{L_{max}} \overline{q_{sf}} \Delta t \right) \right)$$ {#eq-interception-integration-steps}

here, it is assumed that $\overline{q_{sf}}$ is the average snowfall rate over the discrete time interval $\Delta t$. Since $\overline{q_{sf}}$, $C_{lca}$ and $L_{max}$ are temporally constant over the discrete time interval $\Delta t$ they can be moved outside the integral. The analytical solution in @eq-hp98-int-numeric is only possible because canopy snow interception is treated in isolation from the other processes in @eq-canopy-mass-bal.

### Snow Unloading Parameterization Derivations

The steps to get from @eq-hp98-flu to @eq-hp98-exp-decay are:

If the change in canopy snow load due to unloading alone is:

$$
 \frac{d L}{d t} =-q_{unld}(L)
$$ then:

$$\frac{1}{L} d L = -\kappa_{unld} \Delta t$$ $$\int^{L(t+\Delta t)}_{L(t)}\frac{1}{L} dL = -\kappa_{unld}\int^{t+\Delta t}_tdt $$ $$ln(L^{t+\Delta t}) - ln(L^t) = -\kappa_{unld} \Delta t $$ $$ ln \left( \frac{L^{t+\Delta t}}{L^t}\right) = -\kappa_{unld}\Delta t$$ $$L^{t+\Delta t} = L^t exp^{-\kappa_{unld} \Delta t}$$ {#eq-unloading-integration-steps}

note, since $\kappa_{unld}$ is temporally constant it can be moved outside the integral. The analytical solution in @eq-hp98-exp-decay is only possible because unloading is treated in isolation from the other processes in @eq-canopy-mass-bal.
